index:
    path: /
    controller: App\Controller\AboutMeController::index

hobbies:
    path: /hobbies
    controller: App\Controller\HobbiesController::index

hobbie:
    path: /hobbie/{id}
    controller: App\Controller\HobbieController::index