index:
    path: /
    controller: App\Controller\AboutMeController::index

hobbies:
    path: /hobbies
    controller: App\Controller\HobbiesController::index

hobbie:
    path: /hobby/{id}
    controller: App\Controller\HobbyController::index